#pragma once

#define TAPPING_TERM 190
#define QUICK_TAP_TERM 120
#define QUICK_TAP_TERM_PER_KEY
#define FLOW_TAP_TERM 30

#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_WHEEL_MAX_SPEED 2
#define MOUSEKEY_WHEEL_TIME_TO_MAX 10
