VIAL_ENABLE = no
VIA_ENABLE = no
LTO_ENABLE = yes

TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
REPEAT_KEY_ENABLE = no
AUTO_SHIFT_ENABLE = no

ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
