#pragma once

#define VIAL_KEYBOARD_UID {0x77, 0x36, 0x5B, 0xB5, 0xC2, 0xEF, 0xFD, 0x25}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 5, 4 }

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 1
#define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0xd4

#define TAPPING_TERM 160
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
